export const mockData = {
  company: {
    RIC: "AAPL.O",
    ESGCombinedScore: 41.3209155503609,
    ESGControversiesScore: 2.94117647058823,
    ESGEmissionsScore: 97.3404255319149,
    ESGEnvironmentalScore: 65.5090705487122,
    ESGGovernanceScore: 94.3807796779658,
    ESGResourceUseScore: 98.4210526315789,
    ESGSocialScore: 78.1003901553781,
    BusinessSummary:
      "Apple Inc. (Apple) designs, manufactures and markets smartphones, personal computers, tablets, wearables and accessories and sells a range of related services. The Company’s products include iPhone, Mac, iPad, AirPods, Apple TV, Apple Watch, Beats products, HomePod, iPod touch and accessories. The Company operates various platforms, including the App Store, which allows customers to discover and download applications and digital content, such as books, music, video, games and podcasts. Apple offers digital content through subscription-based services, including Apple Arcade, Apple Music, Apple News+, Apple TV+ and Apple Fitness+. Apple also offers a range of other services, such as AppleCare, iCloud, Apple Card and Apple Pay. Apple sells its products and resells third-party products in a range of markets, including directly to consumers, small and mid-sized businesses, and education, enterprise and government customers through its retail and online stores and its direct sales force.",
    CommonName: "Apple Inc",
    HeadquartersCountry: "United States of America",
    PriceClose: 138.88,
    Volume: 0,
  },
  peers: [
    {
      RIC: "HPQ.N",
      ESGCombinedScore: 76.596422483323,
      ESGControversiesScore: 73.5294117647058,
      ESGEmissionsScore: 73.9361702127659,
      ESGEnvironmentalScore: 59.5552071668533,
      ESGGovernanceScore: 94.3895331793663,
      ESGResourceUseScore: 96.3157894736842,
      ESGSocialScore: 80.8021743524894,
      BusinessSummary:
        "HP Inc. is a global provider of personal computing and other access devices, imaging and printing products, and related technologies, solutions and services to individual consumers, small- and medium-sized businesses (SMBs) and large enterprises, including customers in the government, health and education sectors. Its segments include Personal Systems, Printing and Corporate Investments. The Personal Systems segment offers commercial and consumer desktop and notebook personal computers (PCs), workstations, thin clients, commercial mobility devices, retail point-of-sale (POS) systems, displays and peripherals, software, support and services. The Printing segment provides consumer and commercial printer hardware, supplies, services and solutions. The Printing segment is also focused on graphics and three-dimensional (3D) imaging solutions in the commercial and industrial markets. The Corporate Investments segment includes HP Labs and certain business incubation and investment projects.",
      CommonName: "HP Inc",
      HeadquartersCountry: "United States of America",
      PriceClose: 28.29,
      Volume: 3045223,
    },
    {
      RIC: "CSCO.OQ",
      ESGCombinedScore: 54.1220669313148,
      ESGControversiesScore: 20.8333333333333,
      ESGEmissionsScore: 99.3055555555555,
      ESGEnvironmentalScore: 71.2429569528961,
      ESGGovernanceScore: 89.8138335547427,
      ESGResourceUseScore: 99.3333333333333,
      ESGSocialScore: 94.2454864855463,
      BusinessSummary:
        "Cisco Systems, Inc. is engaged in designing and selling a range of technologies that power the Internet. The Company is integrating its platforms across networking, security, collaboration, applications and the cloud. The Company operates through three geographic segments: the Americas; Europe, Middle East, and Africa (EMEA), and Asia Pacific, Japan, and China (APJC). The Company's products categories include Secure, Agile Networks; Internet for the Future; Collaboration; End-to-End Security; Optimized Application Experiences; Other Products, and Services. Secure, Agile Networks consists of its core networking technologies of switching, enterprise routing, wireless, and compute products. Internet for the Future consists of its routed optical networking, public fifth generation (5G), silicon, and optics offerings. Collaboration consists of its Collaboration Devices, Meetings, Calling and contact center offerings. End-to-End Security consists of its overall security offerings.",
      CommonName: "Cisco Systems Inc",
      HeadquartersCountry: "United States of America",
      PriceClose: 43.85,
      Volume: 6705601,
    },
    {
      RIC: "QCOM.OQ",
      ESGCombinedScore: 54.1641570788601,
      ESGControversiesScore: 38.8888888888888,
      ESGEmissionsScore: 98.1770833333333,
      ESGEnvironmentalScore: 67.8057805557401,
      ESGGovernanceScore: 40.993174635949,
      ESGResourceUseScore: 82.1243523316062,
      ESGSocialScore: 87.8676824134324,
      BusinessSummary:
        "Qualcomm Incorporated is engaged in the development and commercialization of foundational technologies for the wireless industry. Its segments include Qualcomm CDMA Technologies (QCT), Qualcomm Technology Licensing (QTL) and Qualcomm Strategic Initiatives (QSI). QCT segment develops and supplies integrated circuits and system software based on third generation/fourth generation/fifth generation (3G/4G/5G) and other technologies for use in wireless voice and data communications, networking, computing, multimedia and global positioning system (GPS) products. QTL segment grants licenses or otherwise provides rights to use portions of its intellectual property portfolio, which, among other rights, includes certain patent rights essential to and/or useful in the manufacture, sale and/or use of certain wireless products, including, without limitation, products implementing CDMA2000, WCDMA, LTE and/or OFDMA-based 5G standards and their derivatives. QSI segment makes strategic investments.",
      CommonName: "Qualcomm Inc",
      HeadquartersCountry: "United States of America",
      PriceClose: 103.88,
      Volume: 6887975,
    },
    {
      RIC: "INTC.OQ",
      ESGCombinedScore: 45.8368481756682,
      ESGControversiesScore: 5.55555555555555,
      ESGEmissionsScore: 97.65625,
      ESGEnvironmentalScore: 89.9311904228113,
      ESGGovernanceScore: 85.3856816387501,
      ESGResourceUseScore: 99.740932642487,
      ESGSocialScore: 83.7889284349289,
      BusinessSummary:
        "Intel Corporation is engaged in designing and manufacturing products and technologies. The Company's segments include Client Computing Group (CCG), Data Center Group (DCG), Internet of Things Group (IOTG), Mobileye, Non-Volatile Memory Solutions Group (NSG) and Programmable Solutions Group (PSG). The CCG segment is focused on long-term operating system, system architecture, hardware, and application integration that enable PC experiences. The DCG segment develops workload-optimized platforms for compute, storage, and network functions. The IOTG segment develops high-performance compute platforms that solve the technology needs for business use cases that scale across vertical industries and embedded markets. The Mobileye segment provides driving assistance and self-driving solutions. The NSG segment provides memory and storage products based on Intel 3D NAND technology. The PSG segment offers programmable semiconductors, primarily FPGAs, structured ASICs, and related products.",
      CommonName: "Intel Corp",
      HeadquartersCountry: "United States of America",
      PriceClose: 27.39,
      Volume: 13515637,
    },
    {
      RIC: "MSI.N",
      ESGCombinedScore: 54.8126320890778,
      ESGControversiesScore: 25,
      ESGEmissionsScore: 96.2686567164179,
      ESGEnvironmentalScore: 70.0678269551895,
      ESGGovernanceScore: 85.2878611214967,
      ESGResourceUseScore: 95.3333333333333,
      ESGSocialScore: 92.2971245542296,
      BusinessSummary:
        "Motorola Solutions, Inc. provides communications and analytics solutions. The Company provides land mobile radio communications (LMR), video security and access control and command center software, video security and analytics, supported by managed and support services. Its segments include Products and Systems Integration Segment, and Software and Services Segment. The Products and Systems Integration segment offers a portfolio of infrastructure, devices, accessories and video security devices, including LMR, public safety long term evolution (LTE) and private LTE, as well as network video management infrastructure, fixed security and mobile video cameras and access control solutions. The Software and Services segment has Software and Services product lines. Software includes public safety and enterprise command center software, unified communications applications, and video software solutions. Services includes range of service offerings, including repair, technical support, others.",
      CommonName: "Motorola Solutions Inc",
      HeadquartersCountry: "United States of America",
      PriceClose: 254.87,
      Volume: 393481,
    },
    {
      RIC: "005930.KS",
      ESGCombinedScore: 59.1056265635835,
      ESGControversiesScore: 35.2941176470588,
      ESGEmissionsScore: 92.0212765957446,
      ESGEnvironmentalScore: 63.2219484882418,
      ESGGovernanceScore: 84.4418525339335,
      ESGResourceUseScore: 92.1052631578947,
      ESGSocialScore: 91.2655123620131,
      BusinessSummary:
        "Samsung Electronics Co Ltd is Korea-based company principally engaged in the manufacture and distribution of electronic products. The Company operates its business through four segments. The Information Technology & Mobile Communications (IM) segment manufactures computers, handhold phones (HHPs), network systems, digital cameras and others. The Device Solutions (DS) segment provides semiconductor and display parts, including dynamic random access memories (DRAMs), flashes, thin film transistor-liquid crystal displays (TFT-LCDs) and others. The Consumer Electronics (CE) segment manufactures color televisions (CTVs), monitors, printers, air conditioners, refrigerators, laundry machines and others. The Harman segment manufactures headunits, infotainment, telematics, speaker, among others. The Company distributes its products within domestic market and to overseas markets.",
      CommonName: "Samsung Electronics Co Ltd",
      HeadquartersCountry: "Korea; Republic (S. Korea)",
      PriceClose: 59400,
      Volume: 12416831,
    },
    {
      RIC: "NOKIA.HE",
      ESGCombinedScore: 49.5827388240775,
      ESGControversiesScore: 8.33333333333333,
      ESGEmissionsScore: 99.2537313432835,
      ESGEnvironmentalScore: 90.008951780888,
      ESGGovernanceScore: 95.1921568627451,
      ESGResourceUseScore: 98,
      ESGSocialScore: 86.8948599318724,
      BusinessSummary:
        "Nokia Oyj is a Finland-based company engaged in the network and Internet protocol (IP) infrastructure, software, and related services market. The Company's businesses include Nokia Networks and Nokia Technologies. The Company's segments include Ultra Broadband Networks, IP Networks and Applications, and Nokia Technologies. The Ultra Broadband Networks segment comprises Mobile Networks and Fixed Networks operating segments. The IP Networks and Applications segment comprises IP/Optical Networks and Applications & Analytics operating segments. The Applications & Analytics operating segment offers software solutions spanning customer experience management, network operations and management, communications and collaboration, policy and charging, as well as Cloud, Internet of things (IoT), security, and analytics platforms that enable digital services providers and enterprises to accelerate and optimize their customer experience. The Company has Comptel Oyj among its subsidiaries.",
      CommonName: "Nokia Oyj",
      HeadquartersCountry: "Finland",
      PriceClose: 4.3965,
      Volume: 11431596,
    },
    {
      RIC: "6758.T",
      ESGCombinedScore: 88.4946657472617,
      ESGControversiesScore: 100,
      ESGEmissionsScore: 95.3125,
      ESGEnvironmentalScore: 87.1688144329896,
      ESGGovernanceScore: 90.8519803087939,
      ESGResourceUseScore: 73.7113402061855,
      ESGSocialScore: 87.7923638035391,
      BusinessSummary:
        "Sony Group Corp is engaged in the games & network services (G&NS), music, movies, electronics products & solutions (EP&S), imaging & sensing solutions (I&SS), finance and other businesses. The G&NS field is involved in the network service business, the manufacture and sale of home video game consoles and software. The music field mainly includes music production, music publishing and video media platform businesses. The film field mainly includes film production, television program production and media network businesses. The EP&S field mainly includes the TV business, audio, video business, still image, video camera business, smartphone business and Internet-related service business. The I&SS field mainly includes the image sensor business. The financial field is involved in the insurance business, which mainly focuses on personal life insurance and non-life insurance, as well as the banking business. The Other fields consist of activities such as disc manufacturing business.",
      CommonName: "Sony Group Corp",
      HeadquartersCountry: "Japan",
      PriceClose: 10700,
      Volume: 5587100,
    },
    {
      RIC: "2357.TW",
      ESGCombinedScore: 1.23821104151552,
      ESGControversiesScore: 100,
      ESGEmissionsScore: null,
      ESGEnvironmentalScore: null,
      ESGGovernanceScore: 3.06910569105691,
      ESGResourceUseScore: null,
      ESGSocialScore: 0.790144435004246,
      BusinessSummary:
        "Asustek Computer Inc is a Taiwan-based company principally engaged in the manufacture and distribution of computers, communication products and consumer electronics (3C). The Company mainly operates through two business segments, including 3C brand segment and other segment. The Company provides desktop motherboards, server motherboards, three-dimension graphic display cards, audio cards, notebook computers, table personal computers (PCs), smart navigation mobile phones, liquid crystal display (LCD) monitors, broadband and communication products, as well as servers, among others. It offers its products under the brand named ASUS. The Company distributes its products primarily in the United States, Canada, Asia, Europe and Africa.",
      CommonName: "Asustek Computer Inc",
      HeadquartersCountry: "Taiwan",
      PriceClose: 234.5,
      Volume: 3387296,
    },
    {
      RIC: "2354.TW",
      ESGCombinedScore: 56.0396099116154,
      ESGControversiesScore: 100,
      ESGEmissionsScore: 93.6274509803921,
      ESGEnvironmentalScore: 68.3227376740295,
      ESGGovernanceScore: 21.8912601626016,
      ESGResourceUseScore: 71.4953271028037,
      ESGSocialScore: 72.8214102111929,
      BusinessSummary:
        "Foxconn Technology Co Ltd is a Taiwan-based company principally engaged in the research and development, manufacture and sale of computers, communications and consumer electronics (3C) products. The Company provides metal shells, structural components, thermal modules and game console assembly products. The Company's products are applied in the manufacture of desktop computers, notebook computers, tablet computers, servers, mobile phones, projectors, e-book readers, digital cameras, servers, workstation radiators and home game consoles. The Company mainly distributes its products in China, the United States and Japan.",
      CommonName: "Foxconn Technology Co Ltd",
      HeadquartersCountry: "Taiwan",
      PriceClose: 45.65,
      Volume: 1715489,
    },
    {
      RIC: "DELL.N",
      ESGCombinedScore: 56.5071555773127,
      ESGControversiesScore: 100,
      ESGEmissionsScore: 75,
      ESGEnvironmentalScore: 57.6210526315789,
      ESGGovernanceScore: 50.6500373810471,
      ESGResourceUseScore: 82.6315789473684,
      ESGSocialScore: 59.2710082788326,
      BusinessSummary:
        "Dell Technologies Inc. is a provider of information technology solutions. The Company operates through two segments: Infrastructure Solutions Group (ISG) and Client Solutions Group (CSG). The ISG segment enables the digital transformation of the Company’s customers through its multi-cloud and big data solutions, which are built upon a modern data center infrastructure. The ISG segment has a portfolio of advanced storage solutions, which includes traditional storage solutions, as well as next-generation storage solutions, while the Company’s server portfolio includes performance rack, blade, tower and hyperscale servers. The CSG segment includes sales to commercial and consumer customers of branded hardware and branded peripherals, as well as services and third-party software and peripherals. The CSG segment also offers attached software, peripherals, and services, including support and deployment, configuration, and extended warranty services.",
      CommonName: "Dell Technologies Inc",
      HeadquartersCountry: "United States of America",
      PriceClose: 39,
      Volume: 936554,
    },
    {
      RIC: "HPE.N",
      ESGCombinedScore: 75.3885702866836,
      ESGControversiesScore: 73.5294117647058,
      ESGEmissionsScore: 85.6382978723404,
      ESGEnvironmentalScore: 61.3531914893617,
      ESGGovernanceScore: 96.6145985825427,
      ESGResourceUseScore: 90,
      ESGSocialScore: 73.8151557201763,
      BusinessSummary:
        "Hewlett Packard Enterprise Company (HPE) is an edge-to-cloud platform as-a-service company. It operates through six segments, namely Compute, High Performance Computing & Artificial Intelligence (HPC & AI), Storage, Intelligent Edge, Financial Services (FS), and Corporate Investments and Other. Compute segment includes both general purpose servers for multi-workload computing and workload optimized servers. Its products include the HPE Proliant rack and tower servers. HPC & AI offers standard and custom hardware and software solutions designed to address customer workloads. The Storage segment offers workload optimized storage product and service offerings. Intelligent Edge offers wired and wireless local area network, campus and data center switching, software-defined wide-area-network, and others. FS provides investment solutions, such as leasing, financing, IT consumption, and others. The Corporate Investments & Other segment include the Communications and Media Solutions business.",
      CommonName: "Hewlett Packard Enterprise Co",
      HeadquartersCountry: "United States of America",
      PriceClose: 14.25,
      Volume: 2505508,
    },
    {
      RIC: "NTAP.OQ",
      ESGCombinedScore: 66.7831162672427,
      ESGControversiesScore: 73.5294117647058,
      ESGEmissionsScore: 62.2340425531914,
      ESGEnvironmentalScore: 53.8835386338186,
      ESGGovernanceScore: 86.3547647998356,
      ESGResourceUseScore: 78.4210526315789,
      ESGSocialScore: 61.8362000963609,
      BusinessSummary:
        "NetApp, Inc. (NetApp) is a cloud-led, data-centric software company. The Company delivers a portfolio of cloud services, and storage infrastructure, powered by intelligent data management software. The Company operates through two segments: Hybrid Cloud and Public Cloud. Its Hybrid Cloud segment offers a portfolio of storage management and infrastructure solutions that help customers recast their data centers with the power of cloud. This portfolio is designed to operate with public clouds to unlock the potential of hybrid, multi-cloud operations. Its Public Cloud segment offers a portfolio of products delivered primarily as-a-service, including related support. This portfolio includes cloud storage and data services, and cloud operations services. It offers a portfolio of cloud-connected all-flash, hybrid-flash, and object storage systems. Its solutions and services are generally available on the public clouds, including Microsoft Azure, Google Cloud Platform and Amazon AWS.",
      CommonName: "NetApp Inc",
      HeadquartersCountry: "United States of America",
      PriceClose: 67.64,
      Volume: 374626,
    },
    {
      RIC: "AMZN.OQ",
      ESGCombinedScore: 42.5634951371706,
      ESGControversiesScore: 2.27272727272727,
      ESGEmissionsScore: 98.1481481481481,
      ESGEnvironmentalScore: 88.4531946578391,
      ESGGovernanceScore: 72.8938643189985,
      ESGResourceUseScore: 81.8681318681318,
      ESGSocialScore: 87.8512109608518,
      BusinessSummary:
        "Amazon.com, Inc. provides a range of products and services to customers. The products offered through its stores include merchandise and content that it purchased for resale and products offered by third-party sellers. It also manufactures and sells electronic devices, including Kindle, Fire tablet, Fire TV, Echo, and Ring, and it develops and produces media content. It operates through three segments: North America, International and Amazon Web Services (AWS). The AWS segment consists of global sales of compute, storage, database, and other services for start-ups, enterprises, government agencies, and academic institutions. It provides advertising services to sellers, vendors, publishers, authors, and others, through programs, such as sponsored advertisements, display, and video advertising. It serves consumers through its online and physical stores. Customers access its offerings through websites, mobile applications, Alexa, devices, streaming, and physically visiting its stores.",
      CommonName: "Amazon.com Inc",
      HeadquartersCountry: "United States of America",
      PriceClose: 89.3,
      Volume: 26787567,
    },
    {
      RIC: "META.OQ",
      ESGCombinedScore: 33.4210955293021,
      ESGControversiesScore: 0.5,
      ESGEmissionsScore: 83.69140625,
      ESGEnvironmentalScore: 49.1189236111111,
      ESGGovernanceScore: 70.8583707143803,
      ESGResourceUseScore: 91.5625,
      ESGSocialScore: 67.0979594723131,
      BusinessSummary:
        "Meta Platforms Inc., formerly Facebook, Inc., builds technologies that help people find communities and grow businesses. The Company's products enable people to connect and share with friends and family through mobile devices, personal computers, virtual reality (VR) headsets, wearables, and in-home devices. The Company operates through two segments: Family of Apps (FoA) and Reality Labs (RL). FoA includes Facebook, Instagram, Messenger, WhatsApp, and other services. RL includes augmented and virtual reality-related consumer hardware, software, and content. Facebook enables people to connect, share, discover and communicate with each other on mobile devices and personal computers. Instagram is a place where people can express themselves through photos, videos, and private messaging, and connect with and shop from their favorite businesses and creators. Messenger is a messaging application for people to connect with friends, family, groups, and businesses across platforms and devices.",
      CommonName: "Meta Platforms Inc",
      HeadquartersCountry: "United States of America",
      PriceClose: 88.91,
      Volume: 13141566,
    },
    {
      RIC: "IBM.N",
      ESGCombinedScore: 74.7663016750624,
      ESGControversiesScore: 100,
      ESGEmissionsScore: 99.90234375,
      ESGEnvironmentalScore: 78.6781442901233,
      ESGGovernanceScore: 54.8281541555779,
      ESGResourceUseScore: 99.0625,
      ESGSocialScore: 96.5574439479263,
      BusinessSummary:
        "International Business Machines Corporation (IBM) is a technology company engaged in providing hybrid cloud and artificial intelligence (AI) solutions. It offers integrated solutions and products that use data and information technology (IT) in industries and business processes. Its segments include Software, Consulting, Infrastructure and Financing. Software segment consists of two business areas: Hybrid Platform & Solutions, which includes software to help clients operate, manage, and optimize their IT resources and business processes within hybrid, multi-cloud environments, and Transaction Processing, which includes software that supports clients’ mission-critical, on-premises workloads in various sectors. Consulting segment is engaged in business transformation, technology consulting and application operations. Infrastructure segment is engaged in hybrid infrastructure and infrastructure support. Financing segment is engaged in client financing and commercial financing business.",
      CommonName: "International Business Machines Corp",
      HeadquartersCountry: "United States of America",
      PriceClose: 136.96,
      Volume: 1303301,
    },
    {
      RIC: "NVDA.OQ",
      ESGCombinedScore: 59.0680200641562,
      ESGControversiesScore: 38.8888888888888,
      ESGEmissionsScore: 95.5729166666666,
      ESGEnvironmentalScore: 68.7515713108735,
      ESGGovernanceScore: 85.5536651087892,
      ESGResourceUseScore: 87.8238341968911,
      ESGSocialScore: 83.0581706605721,
      BusinessSummary:
        "NVIDIA Corporation is a personal computer (PC) gaming market. The Company’s segments include Graphics and Compute & Networking. The Graphics segment includes GeForce graphics processing units (GPUs) for gaming and PCs, the GeForce NOW game streaming service and related infrastructure, and solutions for gaming platforms; Quadro/NVIDIA RTX GPUs for enterprise workstation graphics; virtual GPU software for cloud-based visual and virtual computing; automotive platforms for infotainment systems, and Omniverse software for building three-dimensional (3D) designs and virtual worlds. The Compute & Networking segment includes Data Center platforms and systems for artificial intelligence (AI), high-performance computing (HPC), and accelerated computing; Mellanox networking and interconnect solutions; automotive AI Cockpit, autonomous driving development agreements, and autonomous vehicle solutions; cryptocurrency mining processors (CMP); Jetson for robotics, and NVIDIA AI Enterprise.",
      CommonName: "NVIDIA Corp",
      HeadquartersCountry: "United States of America",
      PriceClose: 134.21,
      Volume: 8176180,
    },
    {
      RIC: "STX.OQ",
      ESGCombinedScore: 62.4774531247967,
      ESGControversiesScore: 100,
      ESGEmissionsScore: 61.3095238095238,
      ESGEnvironmentalScore: 51.027915232358,
      ESGGovernanceScore: 62.2571121846484,
      ESGResourceUseScore: 71.6867469879518,
      ESGSocialScore: 67.9512601437766,
      BusinessSummary:
        "Seagate Technology Holdings plc is a provider of data storage technology and solutions. The Company’s principal products are hard disk drives, including disk drives, hard drives or hard disk drives (HDDs). In addition to HDDs, the Company produces a range of data storage products, including solid state drives (SSDs), solid state hybrid drives (SSHDs), storage subsystems, as well as a scalable edge-to-cloud mass data platform, which includes data transfer shuttles and a storage-as-a-service cloud. The Company’s HDD products are designed for mass capacity storage and legacy markets. Mass capacity storage involves use cases, such as hyperscale data centers and public clouds, as well as emerging use cases. Legacy markets include markets the Company continues to serve. The Company’s HDD and SSD product portfolio includes Serial Advanced Technology Attachment, Serial Attached SCSI and Non-Volatile Memory Express-based designs to support a variety of mass capacity and legacy applications.",
      CommonName: "Seagate Technology Holdings PLC",
      HeadquartersCountry: "Ireland; Republic of",
      PriceClose: 48.49,
      Volume: 894171,
    },
    {
      RIC: "PSTG.N",
      ESGCombinedScore: 19.8888890325227,
      ESGControversiesScore: 100,
      ESGEmissionsScore: 23.9361702127659,
      ESGEnvironmentalScore: 6.33415453527435,
      ESGGovernanceScore: 20.9935224089635,
      ESGResourceUseScore: 3.68421052631578,
      ESGSocialScore: 25.6034565304289,
      BusinessSummary:
        "Pure Storage, Inc. is focused on delivering data storage technologies, products and services. The Company's products and subscription services support a range of structured and unstructured data, at scale and across any data workloads in hybrid and public cloud environments. It also includes production, test and development, analytics, disaster recovery (DR), and backup and recovery. The Company's products and subscription services include FlashArray, FlashArray//C, Cloud Block Store, FlashBlade, Evergreen Subscription, Pure as-a-Service, Pure Fusion, Portworx and Portworx Data Services (PDS). It sells its products and subscription services using a direct sales force and its channel partners. The Company also sells to service providers that deploy its products and offer cloud-based storage services to their customers. The Company operates in multiple locations in the United States and internationally in Africa, Asia, Australia, Europe, and North and South America.",
      CommonName: "Pure Storage Inc",
      HeadquartersCountry: "United States of America",
      PriceClose: 30.34,
      Volume: 689524,
    },
    {
      RIC: "MSFT.OQ",
      ESGCombinedScore: 57.8235423790196,
      ESGControversiesScore: 22.5,
      ESGEmissionsScore: 95.99609375,
      ESGEnvironmentalScore: 78.0878665123456,
      ESGGovernanceScore: 94.1531139887052,
      ESGResourceUseScore: 99.8958333333333,
      ESGSocialScore: 97.2252300725397,
      BusinessSummary:
        "Microsoft Corporation is a technology company. The Company develops and supports software, services, devices, and solutions. Its segments include Productivity and Business Processes, Intelligent Cloud, and More Personal Computing. The Productivity and Business Processes segment consists of products and services in its portfolio of productivity, communication, and information services, spanning a variety of devices and platforms. This segment includes Office Consumer, LinkedIn, dynamics business solutions, and Office Commercial. The Intelligent Cloud segment consists of public, private, and hybrid server products and cloud services that can power modern businesses and developers. This segment includes server products and cloud services, and enterprise services. The More Personal Computing segment consists of products and services that put customers at the centre of the experience with its technology. This segment includes Windows, devices, gaming, and search and news advertising.",
      CommonName: "Microsoft Corp",
      HeadquartersCountry: "United States of America",
      PriceClose: 214.25,
      Volume: 9812133,
    },
    {
      RIC: "WDC.OQ",
      ESGCombinedScore: 65.309878483004,
      ESGControversiesScore: 100,
      ESGEmissionsScore: 76.063829787234,
      ESGEnvironmentalScore: 58.8868980963045,
      ESGGovernanceScore: 45.1160737956128,
      ESGResourceUseScore: 88.9473684210526,
      ESGSocialScore: 79.6348999837372,
      BusinessSummary:
        "Western Digital Corporation (Western Digital) is a developer, manufacturer, and provider of data storage devices based on both flash-based products (Flash) and hard disk drives (HDD) technologies. The Company sells data storage devices and solutions in the United States and in foreign countries through its sales personnel, dealers, distributors, retailers, and subsidiaries. It has two operating segments: flash-based products and hard disk drives. Flash products provide non-volatile data storage based on flash technology. It develops and manufactures solid state storage products for a variety of applications, including enterprise or cloud storage, client storage, automotive, mobile devices and removable memory devices. HDD products provide non-volatile data storage by recording magnetic information on a rotating disk. It develops and manufactures various recording heads and magnetic media used in its HDD products.",
      CommonName: "Western Digital Corp",
      HeadquartersCountry: "United States of America",
      PriceClose: 33.71,
      Volume: 1108402,
    },
    {
      RIC: "ANET.N",
      ESGCombinedScore: 63.4593801286733,
      ESGControversiesScore: 100,
      ESGEmissionsScore: 84.0277777777777,
      ESGEnvironmentalScore: 62.1579896326347,
      ESGGovernanceScore: 73.0687003740653,
      ESGResourceUseScore: 80.6666666666666,
      ESGSocialScore: 54.487830614209,
      BusinessSummary:
        "Arista Networks, Inc. is a supplier of cloud networking solutions that use software to address the needs of Internet companies, cloud service providers and enterprises. The Company cloud networking solutions consist of its Extensible Operating System (EOS), a set of network applications and its Gigabit Ethernet switching and routing platforms. Its cognitive single-tier Spline campus network extends EOS across the data center and campus wired and wireless workspace. The Company’s CloudVision is a network-wide approach for workload orchestration and automation, leverages EOS and Cognitive WiFi features, to deliver cloud networking solutions to its enterprise customers. The Company sells its products through both its direct sales force and its channel partners. The Company’s end customers span a range of industries and include large Internet companies, service providers, financial services organizations, government agencies, media and entertainment companies and others.",
      CommonName: "Arista Networks Inc",
      HeadquartersCountry: "United States of America",
      PriceClose: 131.07,
      Volume: 821825,
    },
    {
      RIC: "GOOGL.OQ",
      ESGCombinedScore: 44.8915261660832,
      ESGControversiesScore: 7.5,
      ESGEmissionsScore: 94.62890625,
      ESGEnvironmentalScore: 76.8118248456789,
      ESGGovernanceScore: 83.1255275771254,
      ESGResourceUseScore: 96.9791666666666,
      ESGSocialScore: 83.2107990429904,
      BusinessSummary:
        "Alphabet Inc. is a holding company. The Company's segments include Google Services, Google Cloud, and Other Bets. The Google Services segment includes products and services such as ads, Android, Chrome, hardware, Google Maps, Google Play, Search, and YouTube. The Google Cloud segment includes Google's infrastructure and platform services, collaboration tools, and other services for enterprise customers. The Other Bets segment includes earlier stage technologies that are further afield from its core Google business, and it includes the sale of health technology and Internet services. Its Google Cloud provides enterprise-ready cloud services, including Google Cloud Platform and Google Workspace. Google Cloud Platform enables developers to build, test, and deploy applications on its infrastructure. The Company's Google Workspace collaboration tools include applications, such as Gmail, Docs, Drive, Calendar, Meet, and various others. The Company also has various hardware products.",
      CommonName: "Alphabet Inc",
      HeadquartersCountry: "United States of America",
      PriceClose: 83.43,
      Volume: 14785692,
    },
    {
      RIC: "MU.OQ",
      ESGCombinedScore: 72.8276587850361,
      ESGControversiesScore: 100,
      ESGEmissionsScore: 78.7425149700598,
      ESGEnvironmentalScore: 64.3329481421558,
      ESGGovernanceScore: 69.6954911853446,
      ESGResourceUseScore: 88.150289017341,
      ESGSocialScore: 80.9039135554287,
      BusinessSummary:
        "Micron Technology, Inc. is a provider of memory and storage solutions. The Company's product portfolio includes dynamic random-access memory (DRAM), negative-AND (NAND), three-dimensional (3D) XPoint memory, and NOR, solid-state drives, graphics and high bandwidth memory (HBM), managed NAND and multichip packages. Its brands include Micron and Crucial. The Company's segments include Compute and Networking Business Unit (CNBU) includes memory products sold into client, cloud server, enterprise, graphics, and networking markets; Mobile Business Unit (MBU) includes memory and storage products sold into smartphone and other mobile-device markets; Storage Business Unit (SBU) includes solid state drives (SSDs) and component-level solutions sold into enterprise and cloud, client, and consumer storage markets and other discrete storage products; Embedded Business Unit (EBU) includes memory and storage products sold into automotive, industrial, and consumer markets.",
      CommonName: "Micron Technology Inc",
      HeadquartersCountry: "United States of America",
      PriceClose: 53.48,
      Volume: 3821295,
    },
    {
      RIC: "AMD.OQ",
      ESGCombinedScore: 69.7946966701775,
      ESGControversiesScore: 77.7777777777777,
      ESGEmissionsScore: 91.9270833333333,
      ESGEnvironmentalScore: 70.0123507917793,
      ESGGovernanceScore: 60.0004529242794,
      ESGResourceUseScore: 95.5958549222797,
      ESGSocialScore: 75.5723080641025,
      BusinessSummary:
        "Advanced Micro Devices, Inc. is a global semiconductor company. Its segments include Computing and Graphics, and Enterprise, Embedded and Semi-Custom. The Computing and Graphics segment primarily includes desktop and notebook microprocessors, accelerated processing units that integrate microprocessors and graphics, chipsets, discrete graphics processing units (GPUs), data center and professional GPUs, and development services. It may also sell or license portions of its intellectual property (IP) portfolio. The Enterprise, Embedded and Semi-Custom segment primarily includes server and embedded processors, semi-custom system-on-chip (SoC) products, development services, and technology for game consoles, and it may also sell or license portions of its IP portfolio. Its microprocessor customers consist primarily of original equipment manufacturers (OEMs), large public cloud service providers, original design manufacturers (ODMs), system integrators, and independent distributors.",
      CommonName: "Advanced Micro Devices Inc",
      HeadquartersCountry: "United States of America",
      PriceClose: 60.11,
      Volume: 13801049,
    },
    {
      RIC: "AMAT.OQ",
      ESGCombinedScore: 80.7955445530425,
      ESGControversiesScore: 100,
      ESGEmissionsScore: 75.78125,
      ESGEnvironmentalScore: 82.6138868822241,
      ESGGovernanceScore: 89.8779785575176,
      ESGResourceUseScore: 97.6683937823834,
      ESGSocialScore: 73.9686083109257,
      BusinessSummary:
        "Applied Materials, Inc. provides manufacturing equipment, services and software to the semiconductor, display, and related industries. The Company operates through three segments: Semiconductor Systems, Applied Global Services, and Display and Adjacent Markets. Its Semiconductor Systems segment primarily consists of capital equipment used to fabricate semiconductor chips. Its Applied Global Services segment provides integrated solutions to optimize equipment and fab performance and productivity, including spares, upgrades, services, certain remanufactured old equipment and factory automation software for semiconductor, display and solar products. Its Display and Adjacent Markets segment includes products for manufacturing liquid crystal and organic light-emitting diode (OLED) displays, and other display technologies for televisions, monitors, laptops, personal computers, electronic tablets, smart phones, and other consumer-oriented devices and equipment upgrades.",
      CommonName: "Applied Materials Inc",
      HeadquartersCountry: "United States of America",
      PriceClose: 86.3,
      Volume: 2516111,
    },
    {
      RIC: "XRX.OQ",
      ESGCombinedScore: 73.0562180894815,
      ESGControversiesScore: 100,
      ESGEmissionsScore: 96.4285714285714,
      ESGEnvironmentalScore: 96.0751488095238,
      ESGGovernanceScore: 51.8639951867957,
      ESGResourceUseScore: 96.4285714285714,
      ESGSocialScore: 71.2059594479993,
      BusinessSummary:
        "Xerox Holdings Corporation is a workplace technology company, building and integrating software and hardware for enterprises. It has developed the copier, the Ethernet, the laser printer and more. The Company has capabilities in artificial intelligence (AI), augmented reality (AR) driven service experiences, robotic process automation (RPA), sensors and services for Internet of Things (IoT), three-dimensional (3D) printing and Clean Technologies (clean tech). Its segments include Workplace Solutions which is made up of two strategic product groups, Entry and Mid-Range, which share common technology, manufacturing and product platforms; Production Solutions are designed for customers in graphic communications, in-plant and production print environments with high-volume printing requirements; Xerox Services includes a continuum of solutions and services that helps its customers; and FITTLE is engaged in financing for direct channel customer purchases of Xerox equipment.",
      CommonName: "Xerox Holdings Corp",
      HeadquartersCountry: "United States of America",
      PriceClose: 13.94,
      Volume: 675174,
    },
    {
      RIC: "JNPR.N",
      ESGCombinedScore: 84.4392372370974,
      ESGControversiesScore: 100,
      ESGEmissionsScore: 78.3582089552238,
      ESGEnvironmentalScore: 88.8063144485187,
      ESGGovernanceScore: 85.5541062291663,
      ESGResourceUseScore: 88.6666666666666,
      ESGSocialScore: 80.8093591801457,
      BusinessSummary:
        "Juniper Networks, Inc. is engaged in artificial intelligence (AI) networking, cloud, and connected security solutions. The Company designs, develops, and sells products and services for high-performance networks to enable customers to build networks for their businesses. It sells high-performance networking product offerings with various customer solution categories, such as AI-Driven Enterprise, Automated WAN Solutions, and Cloud-Ready Data Center, and its connected security products are sold in each category. Its AI-Driven Enterprise encompasses a client-to-cloud portfolio, cloud-delivered campus-wired and wireless solutions of Mist and EX switches, and its SD-WAN portfolio, which includes about 128 Technology and Branch SRX solutions. Its Automated WAN Solutions includes MX and PTX product lines, and ACX product line targeting the Metro market. Its Cloud-Ready Data Center includes QFX product line, Apstra, and Contrail product lines, along with its security portfolio of SRX.",
      CommonName: "Juniper Networks Inc",
      HeadquartersCountry: "United States of America",
      PriceClose: 30.12,
      Volume: 1347031,
    },
    {
      RIC: "CIEN.N",
      ESGCombinedScore: 66.6712840154751,
      ESGControversiesScore: 100,
      ESGEmissionsScore: 63.4328358208955,
      ESGEnvironmentalScore: 42.3417514503606,
      ESGGovernanceScore: 78.8442677682044,
      ESGResourceUseScore: 27.3333333333333,
      ESGSocialScore: 68.3031674208144,
      BusinessSummary:
        "Ciena Corporation (Ciena)is a networking systems, services and software company. The Company operates through four segments: Networking Platforms; Platform Software and Services; Blue Planet Automation Software and Services; and Global Services. The Networking Platforms segment consists of its Converged Packet Optical and Packet Networking portfolios. The Platform Software and Services segment provides analytics, data, and planning tools to assist customers in managing Ciena's Networking Platforms products in their networks. The Blue Planet Automation Software and Services segment includes micro-services, standards-based open software suite, together with related services, that enables customers to implement large-scale software and information technology (IT)-led operations support system transformations. The Global Services segment includes the sales of a range of Ciena's services for maintenance support, and training, installation and deployment and network design activities.",
      CommonName: "Ciena Corp",
      HeadquartersCountry: "United States of America",
      PriceClose: 45.95,
      Volume: 470544,
    },
    {
      RIC: "LYFT.OQ",
      ESGCombinedScore: 22.634076338094,
      ESGControversiesScore: 5.5,
      ESGEmissionsScore: 30.2238805970149,
      ESGEnvironmentalScore: 6.71641791044775,
      ESGGovernanceScore: 39.0734886099649,
      ESGResourceUseScore: null,
      ESGSocialScore: 52.0896572521242,
      BusinessSummary:
        "Lyft, Inc. owns and operates multimodal transportation networks in the United States and Canada that offer access to a variety of transportation options through its platform and mobile-based applications. The Lyft Platform provides a marketplace where drivers are matched with riders via the Lyft App. Transportation options through the Company's platform and mobile-based applications are comprised of its ridesharing marketplace that connects drivers and riders in cities across the United States and Canada; Lyft's network of Light Vehicles; the Express Drive program, where drivers can enter into short-term rental agreements with Flexdrive or a third party for vehicles is used to provide ridesharing services, and Lyft Rentals, a consumer offering for users who want to rent a car for a fixed period of time for personal use, and Lyft Driver Centers and Lyft Auto Care, where drivers and riders can request auto maintenance and collision repair services offered through the Lyft Platform.",
      CommonName: "Lyft Inc",
      HeadquartersCountry: "United States of America",
      PriceClose: 13.72,
      Volume: 3850960,
    },
    {
      RIC: "PINS.N",
      ESGCombinedScore: 30.8974213517488,
      ESGControversiesScore: 26,
      ESGEmissionsScore: null,
      ESGEnvironmentalScore: null,
      ESGGovernanceScore: 34.5115546218487,
      ESGResourceUseScore: null,
      ESGSocialScore: 49.7555740627602,
      BusinessSummary:
        "Pinterest, Inc. (Pinterest) is a visual discovery engine company. On Pinterest, people discover and personalize visual content, which is called Pins. Pins are created when Pinners, creators and businesses create new content for or save existing Web content to its platform. It offers several types of Pins on its platform, including Standard Pins, Product Pins, Video Pins and Idea Pins. Its Standard Pins include static images that link to content from around the Web highlighting products, recipes, style and home inspiration, do it yourself (DIY), and others. Its Product Pins include items from its catalogue inventory that can be purchased and include metadata on prices and stock availability. Its Video Pins include short videos from businesses that link to content on topics like cooking, beauty and DIY projects. It also provides THE YES app, a shopping platform for fashion that enables users to shop a personalized feed based on the user's active input on brand, style, and size.",
      CommonName: "Pinterest Inc",
      HeadquartersCountry: "United States of America",
      PriceClose: 22.39,
      Volume: 2624742,
    },
    {
      RIC: "AVGO.OQ",
      ESGCombinedScore: 46.191073234694,
      ESGControversiesScore: 16.6666666666666,
      ESGEmissionsScore: 59.6354166666666,
      ESGEnvironmentalScore: 73.2851497341054,
      ESGGovernanceScore: 74.0753530351298,
      ESGResourceUseScore: 58.8082901554404,
      ESGSocialScore: 78.4770088026794,
      BusinessSummary:
        "Broadcom Inc. is a technology company. The Company designs, develops and supplies a range of semiconductor and infrastructure software solutions. The Company operates through two segments: semiconductor solutions and infrastructure software. Its semiconductor solutions segment includes all of its product lines and intellectual property (IP) licensing. It provides semiconductor solutions for managing the movement of data in data center, telecom, enterprise and embedded networking applications. It also provides a variety of radio frequency (RF) semiconductor devices, wireless connectivity solutions and custom touch controllers for the wireless market. Its infrastructure software segment includes its mainframe, distributed and cyber security solutions, and its fiber channel storage area networking (FC SAN) business. The Company's mainframe software provides DevOps, AIOps, Security and Data Management Systems solutions.",
      CommonName: "Broadcom Inc",
      HeadquartersCountry: "United States of America",
      PriceClose: 444.12,
      Volume: 918995,
    },
    {
      RIC: "NFLX.OQ",
      ESGCombinedScore: 23.8861879586722,
      ESGControversiesScore: 13,
      ESGEmissionsScore: 77.24609375,
      ESGEnvironmentalScore: 35.9505208333333,
      ESGGovernanceScore: 35.8415437807988,
      ESGResourceUseScore: 56.3541666666666,
      ESGSocialScore: 33.1203111374398,
      BusinessSummary:
        "Netflix, Inc. is an entertainment services company. The Company has paid streaming memberships in over 190 countries, and it allows members to watch a variety of television (TV) series, documentaries, feature films and mobile games across a variety of genres and languages. Its members can watch as much as they want, anytime, anywhere, on any Internet-connected screen. Members can play, pause and resume watching, without commercials. Additionally, the Company offers its digital versatile disk (DVD) -by-mail service in the United States. It offers a variety of streaming membership plans, the price of which varies by country and the features of the plan. The pricing of its plans ranges from U.S. dollar equivalent of approximately $2 to $27 per month. It members can watch streaming content through a host of Internet-connected devices, including TVs, digital video players, TV set-top boxes and mobile devices. It acquires, licenses and produces content, including original programming.",
      CommonName: "Netflix Inc",
      HeadquartersCountry: "United States of America",
      PriceClose: 269.06,
      Volume: 1911926,
    },
    {
      RIC: "UBER.N",
      ESGCombinedScore: 37.6847392186339,
      ESGControversiesScore: 2.5,
      ESGEmissionsScore: 67.2885572139303,
      ESGEnvironmentalScore: 66.711159081728,
      ESGGovernanceScore: 93.0764206705239,
      ESGResourceUseScore: 84.5052083333333,
      ESGSocialScore: 51.5488309741261,
      BusinessSummary:
        "Uber Technologies, Inc. (Uber) develops and operates technology applications supporting a variety of offerings on its platform. The Company connects consumers with providers of ride services, merchants, and food delivery services as well as public transportation networks. Its segments include Mobility, Delivery, and Freight. Mobility refers to products that connect consumers with Mobility drivers who provide rides in a variety of vehicles, such as cars, auto rickshaws, motorbikes, minibuses, or taxis. Mobility also includes activity related to its financial partnership’s offerings. Delivery offering allows consumers to search for and discover local restaurants, order meal, and either pick-up at the restaurant or have the meal delivered and, in certain markets, also includes offerings for grocery, alcohol and convenience store delivery as well as other goods. The Freight segment connects carriers with shippers on its platform, gives carriers upfront, and enables to book a shipment.",
      CommonName: "Uber Technologies Inc",
      HeadquartersCountry: "United States of America",
      PriceClose: 28.39,
      Volume: 5161975,
    },
    {
      RIC: "CDW.OQ",
      ESGCombinedScore: 61.0967864991494,
      ESGControversiesScore: 100,
      ESGEmissionsScore: 59.08203125,
      ESGEnvironmentalScore: 41.0807291666666,
      ESGGovernanceScore: 49.1256886269848,
      ESGResourceUseScore: 83.8541666666666,
      ESGSocialScore: 81.9720427116892,
      BusinessSummary:
        "CDW Corporation is a technology company that is a multi-brand provider of information technology (IT) solutions to small, medium and large business, government, education and healthcare customers in the United States, the United Kingdom and Canada. The Company’s array of offerings ranges from discrete hardware and software products to integrated IT solutions and services that include on-premises, hybrid and cloud capabilities across hybrid infrastructure, digital experience and security. The Company's business segments include Corporate, Small Business, and Public. The Corporate segment primarily serves the United States private sector business customers. The Small Business segment primarily serves the United States private sector business customers. The Public segment comprises government agencies, education, and healthcare institutions in the United States. The Company's solutions are delivered in physical, virtual and cloud-based environments.",
      CommonName: "CDW Corp",
      HeadquartersCountry: "United States of America",
      PriceClose: 172.83,
      Volume: 389527,
    },
    {
      RIC: "TXN.OQ",
      ESGCombinedScore: 83.0041102309193,
      ESGControversiesScore: 100,
      ESGEmissionsScore: 99.21875,
      ESGEnvironmentalScore: 97.5706155755946,
      ESGGovernanceScore: 54.431549986089,
      ESGResourceUseScore: 98.7046632124352,
      ESGSocialScore: 89.7269913407498,
      BusinessSummary:
        "Texas Instruments Incorporated designs, makes and sells semiconductors to electronics designers and manufacturers across the world. The Company operates through two segments: Analog and Embedded Processing. The Company's Analog segment product lines include Power and Signal Chain. Power includes products that help customers manage power in electronic systems. Signal Chain includes products that sense, condition and measure signals to allow information to be transferred or converted for further processing and control. The Embedded Processing segment includes microcontrollers, digital signal processors (DSPs), and applications processors. Microcontrollers are self-contained systems with a processor core, memory and peripherals that are designed to control a set of specific tasks for electronic equipment. DSPs perform mathematical computations to process or improve digital data. Applications processors are designed for specific computing activities.",
      CommonName: "Texas Instruments Inc",
      HeadquartersCountry: "United States of America",
      PriceClose: 156.52,
      Volume: 1845156,
    },
    {
      RIC: "GLW.N",
      ESGCombinedScore: 68.2320779541306,
      ESGControversiesScore: 100,
      ESGEmissionsScore: 72.0588235294117,
      ESGEnvironmentalScore: 61.4926488208511,
      ESGGovernanceScore: 74.9854968638521,
      ESGResourceUseScore: 72.4299065420561,
      ESGSocialScore: 70.0854677666311,
      BusinessSummary:
        "Corning Incorporated is a materials science technology and innovation company. The Company operates through five segments: Display Technologies, Optical Communications, Specialty Materials, Environmental Technologies and Life Sciences. The Display Technologies segment manufactures glass substrates for flat panel liquid crystal displays and other high-performance display panels. The Optical Communications segment manufactures carrier network and enterprise network components for the telecommunications industry. The Specialty Materials segment manufactures products that provide more than 150 material formulations for glass, glass ceramics and fluoride crystals. The Environmental Technologies segment manufactures ceramic substrates and filters for automotive and diesel applications. The Life Sciences segment manufactures glass and plastic labware, equipment, media, serum and reagents enabling workflow solutions for drug discovery and bioproduction.",
      CommonName: "Corning Inc",
      HeadquartersCountry: "United States of America",
      PriceClose: 32.89,
      Volume: 976372,
    },
    {
      RIC: "NXPI.OQ",
      ESGCombinedScore: 76.847136341438,
      ESGControversiesScore: 100,
      ESGEmissionsScore: 83.0729166666666,
      ESGEnvironmentalScore: 67.6235488583692,
      ESGGovernanceScore: 83.4030612244898,
      ESGResourceUseScore: 96.6321243523316,
      ESGSocialScore: 79.5819121575779,
      BusinessSummary:
        "NXP Semiconductors NV (NXP) is The Netherlands-based holding company. The Company operates as a semiconductor company. The Company provides high performance mixed signal analog-digital (mixed A/D) and standard product solutions. Its product solutions are used in a range of end-market applications, including automotive, personal security and identification, industrial & Internet of Things (IoT), wireless and wireline infrastructure, mobile communications, multi-market industrial, consumer and computing. It engages with global original equipment manufacturers (OEMs). The Company sells products in all geographic regions and countries: China, USA, Japan, Malaysia, South Korea, Germany, The Netherlands, and others.",
      CommonName: "NXP Semiconductors NV",
      HeadquartersCountry: "Netherlands",
      PriceClose: 144.85,
      Volume: 1015271,
    },
    {
      RIC: "ADI.OQ",
      ESGCombinedScore: 74.9750491862579,
      ESGControversiesScore: 100,
      ESGEmissionsScore: 86.1979166666666,
      ESGEnvironmentalScore: 82.5097017634664,
      ESGGovernanceScore: 66.6781836889722,
      ESGResourceUseScore: 62.4352331606217,
      ESGSocialScore: 74.5237051890674,
      BusinessSummary:
        "Analog Devices, Inc. is a semiconductor company. The Company designs, manufactures, tests and markets a portfolio of solutions, including integrated circuits (ICs), software and subsystems that leverage analog, mixed-signal and digital signal processing technologies. Its products include data converters, amplifiers, power management, radio frequency (RF) ICs, edge processors and other sensors. The Company's ICs are designed to address a range of real-world signal processing applications. Its IC product portfolio includes both general-purpose products used by a range of customers and applications, as well as application-specific products designed for specific target markets. The Company's product offerings include more than 75,000 stock-keeping units (SKUs) that can be aggregated into various general categories, such as analog and mixed signal, power management and reference, amplifiers/RF and microwave, sensors and actuators, and digital signal processing and system products (DSPs).",
      CommonName: "Analog Devices Inc",
      HeadquartersCountry: "United States of America",
      PriceClose: 138.02,
      Volume: 1581013,
    },
    {
      RIC: "MCHP.OQ",
      ESGCombinedScore: 70.1118779762819,
      ESGControversiesScore: 100,
      ESGEmissionsScore: 88.7434554973822,
      ESGEnvironmentalScore: 71.1339288877329,
      ESGGovernanceScore: 62.9373875742678,
      ESGResourceUseScore: 47.1354166666666,
      ESGSocialScore: 73.7167442237202,
      BusinessSummary:
        "Microchip Technology Incorporated is a provider of smart, connected and secure embedded control solutions. The Company's product portfolio is a combination of hardware, software and services. Its synergistic product portfolio empowers disruptive growth trends, including fifth generation, data centers, artificial intelligence and machine learning, Internet of things and edge computing, advanced driver assist systems and autonomous driving, and electric vehicles. It operates through two segments. In the semiconductor products segment, the Company designs, develops, manufactures and markets microcontrollers, development tools and analog, interface, mixed-signal, timing, wired and wireless connectivity devices, and memory products. The technology licensing segment includes sales and licensing of the Company's intellectual property. Its solutions serve approximately 124,000 customers across the industrial, automotive, consumer, aerospace and defense, communications, and computing markets.",
      CommonName: "Microchip Technology Inc",
      HeadquartersCountry: "United States of America",
      PriceClose: 59.46,
      Volume: 2228668,
    },
    {
      RIC: "SNAP.N",
      ESGCombinedScore: 34.3052816606262,
      ESGControversiesScore: 7,
      ESGEmissionsScore: 88.9303482587064,
      ESGEnvironmentalScore: 67.7878070916782,
      ESGGovernanceScore: 41.5875818187903,
      ESGResourceUseScore: 73.3072916666666,
      ESGSocialScore: 82.7109859460277,
      BusinessSummary:
        "Snap Inc. is a camera company. The Company's flagship product, Snapchat, is a camera application that helps people communicate visually with friends and family through short videos and images called Snaps. Snapchat is its core mobile device application and contains five tabs. Its tabs include Camera, Communication, Snap Map, Stories and Spotlight. The Camera is the starting point for creation in Snapchat. Snapchat opens directly to the Camera, making it easy to create a Snap and send it to friends. Communication allows users to send Snaps to friends collectively or individually, through its messaging architecture. Snap Map is a live and personalized map that allows Snapchatters to connect with friends and explore what is going on in their local area. Stories feature content from a Snapchatter's friends, its community, and its content partners. Spotlight is a way to share user-generated content with the entire Snapchat community. Its advertising products include Snap Ads and AR Ads.",
      CommonName: "Snap Inc",
      HeadquartersCountry: "United States of America",
      PriceClose: 9.14,
      Volume: 6589296,
    },
    {
      RIC: "TWLO.N",
      ESGCombinedScore: 49.0531725471466,
      ESGControversiesScore: 81,
      ESGEmissionsScore: 14.0625,
      ESGEnvironmentalScore: 7.15277777777777,
      ESGGovernanceScore: 50.7483469857001,
      ESGResourceUseScore: 12.0833333333333,
      ESGSocialScore: 61.6821397639613,
      BusinessSummary:
        "Twilio Inc. offers cloud communications platform, which enables developers to build, scale and operate real-time communications within software applications. The Company offers a customer engagement platform with software designed to address specific use cases, like account security and contact centers, and a set of Application Programming Interfaces (APIs). It also offers a set of APIs that enable developers to embed voice, messaging, video and email capabilities into their applications, and are designed to support all the fundamental ways humans communicate to address any communication market. The Super Network is its software layer that allows its customers' software to communicate with connected devices globally. It interconnects with communications networks and inbox service providers around the world. The Super Network also contains a set of APIs giving its customers access to foundational components of its platform, like phone numbers and session initiation protocol Trunking.",
      CommonName: "Twilio Inc",
      HeadquartersCountry: "United States of America",
      PriceClose: 42.74,
      Volume: 4797489,
    },
    {
      RIC: "DIS.N",
      ESGCombinedScore: 36.5012904104276,
      ESGControversiesScore: 3.33333333333333,
      ESGEmissionsScore: 74.6710526315789,
      ESGEnvironmentalScore: 57.7108868060562,
      ESGGovernanceScore: 50.6930000939533,
      ESGResourceUseScore: 92.8082191780822,
      ESGSocialScore: 87.109020364021,
      BusinessSummary:
        "The Walt Disney Company is a worldwide entertainment company. The Company’s segments include Disney Media and Entertainment Distribution (DMED), and Disney Parks, Experiences and Products (DPEP). The DMED segment encompasses the Company’s global film and episodic television content production and distribution activities. The Company’s DMED’s lines of business consists of Linear Networks, Direct-to-Consumer and Content Sales/Licensing. The Company’s DPEP segment business consists of sale of admissions to theme parks, the sale of food, beverage and merchandise at its theme parks and resorts, sales of cruise vacations, sales and rentals of vacation club properties, royalties from licensing its intellectual properties (IP) for use on consumer goods and the sale of branded merchandise. The Content Sales/Licensing business consist of selling film and episodic television content in the television and subscription video-on-demand (TV/SVOD) and home entertainment markets.",
      CommonName: "Walt Disney Co",
      HeadquartersCountry: "United States of America",
      PriceClose: 99.58,
      Volume: 3244994,
    },
    {
      RIC: "TSLA.OQ",
      ESGCombinedScore: 34.2768563744753,
      ESGControversiesScore: 3.57142857142857,
      ESGEmissionsScore: 68.1818181818181,
      ESGEnvironmentalScore: 73.3948503772292,
      ESGGovernanceScore: 64.7832595726798,
      ESGResourceUseScore: 55.2863436123348,
      ESGSocialScore: 58.1935471955856,
      BusinessSummary:
        "Tesla, Inc. designs, develops, manufactures, sells and leases fully electric vehicles and energy generation and storage systems, and offer services related to its products. The Company's automotive segment includes the design, development, manufacturing, sales, and leasing of electric vehicles as well as sales of automotive regulatory credits. Additionally, the automotive segment is also comprised of services and other, which includes non-warranty after-sales vehicle services, sales of used vehicles, retail merchandise, sales by its acquired subsidiaries to third party customers, and vehicle insurance. Its energy generation and storage segment includes the design, manufacture, installation, sales and leasing of solar energy generation and energy storage products and related services and sales of solar energy systems incentives. Its automotive products include Model 3, Model Y, Model S and Model X. Powerwall and Megapack are its lithium-ion battery energy storage products.",
      CommonName: "Tesla Inc",
      HeadquartersCountry: "United States of America",
      PriceClose: 215.31,
      Volume: 11089977,
    },
    {
      RIC: "JBL.N",
      ESGCombinedScore: 68.9357416512916,
      ESGControversiesScore: 100,
      ESGEmissionsScore: 73.0392156862745,
      ESGEnvironmentalScore: 70.1128402475296,
      ESGGovernanceScore: 69.3106019058689,
      ESGResourceUseScore: 61.214953271028,
      ESGSocialScore: 67.1771984854271,
      BusinessSummary:
        "Jabil Inc. is a provider of manufacturing services and solutions. The Company provides comprehensive electronics design, production and product management services to companies in various industries and end markets. The Company has two segments: Electronics Manufacturing Services (EMS) and Diversified Manufacturing Services (DMS). EMS segment is focused on leveraging information technology (IT), supply chain design and engineering, technologies centered on core electronics, sharing of its manufacturing infrastructure and the ability to serve a range of markets. EMS segment produces product to the customers primarily in the fifth generation, wireless and cloud, digital print and retail, industrial and semi-cap, and networking and storage industries. DMS segment is focused on providing engineering solutions, with a focus on material sciences, technologies and healthcare. DMS segment includes customers primarily in the automotive and transportation, connected devices, and other.",
      CommonName: "Jabil Inc",
      HeadquartersCountry: "United States of America",
      PriceClose: 63.98,
      Volume: 249148,
    },
    {
      RIC: "LRCX.OQ",
      ESGCombinedScore: 73.1108449177481,
      ESGControversiesScore: 77.7777777777777,
      ESGEmissionsScore: 93.4895833333333,
      ESGEnvironmentalScore: 68.7482729996089,
      ESGGovernanceScore: 51.2610317788061,
      ESGResourceUseScore: 89.8963730569948,
      ESGSocialScore: 89.5259354878747,
      BusinessSummary:
        "Lam Research Corporation is a supplier of wafer fabrication equipment and services to the semiconductor industry. The Company designs, manufactures, markets, refurbishes, and services semiconductor processing equipment used in the fabrication of integrated circuits. Its products and services are designed to help its customers build devices that are used in a variety of electronic products, including mobile phones, personal computers, servers, wearables, automotive vehicles, and data storage devices. Its product families include ALTUS, SABRE, SOLA, SPEED, Striker, VECTOR, Flex, Kiyo, Syndion, Versys Metal, Coronus, DV-Prime , Da Vinci , EOS , and SP Series. Its customer base includes semiconductor memory, foundry, and integrated device manufacturers (IDMs) that make products, such as non-volatile memory (NVM), dynamic random-access memory (DRAM) and logic devices. It offers services in areas, such as nanoscale applications enablement, chemistry, plasma and fluidics, and others.",
      CommonName: "Lam Research Corp",
      HeadquartersCountry: "United States of America",
      PriceClose: 393.42,
      Volume: 608878,
    },
    {
      RIC: "KLAC.OQ",
      ESGCombinedScore: 58.2096597007648,
      ESGControversiesScore: 100,
      ESGEmissionsScore: 68.4895833333333,
      ESGEnvironmentalScore: 49.5521014394476,
      ESGGovernanceScore: 64.9137181523675,
      ESGResourceUseScore: 52.0725388601036,
      ESGSocialScore: 60.4429999807516,
      BusinessSummary:
        "KLA Corporation (KLA) is a supplier of process control and yield management solutions and services for the semiconductor and related electronics industries. The Company offers a portfolio of device manufacturing, inspection and metrology products and related service, software and other offerings support research and development (R&D) and manufacturing of integrated circuits (IC), wafers and reticles. It also offers technologically advanced, yield-enhancing and process-enabling solutions to address various manufacturing stages of Printed Circuit Boards (PCB), Flat Panel Displays (FPD), Specialty Semiconductor Devices (SD) and other electronic components. Its segment includes Semiconductor Process Control; Specialty Semiconductor Process; PCB, Display and Component Inspection, and Other. The Semiconductor Process Control segment provides a portfolio of inspection, metrology and data analytics products as well as related service offerings.",
      CommonName: "KLA Corp",
      HeadquartersCountry: "United States of America",
      PriceClose: 314.44,
      Volume: 701884,
    },
    {
      RIC: "ON.OQ",
      ESGCombinedScore: 76.4975161504758,
      ESGControversiesScore: 100,
      ESGEmissionsScore: 85.6770833333333,
      ESGEnvironmentalScore: 58.2868542460107,
      ESGGovernanceScore: 86.6828758934671,
      ESGResourceUseScore: 63.4715025906735,
      ESGSocialScore: 83.5686886003952,
      BusinessSummary:
        "ON Semiconductor Corporation provides intelligent sensing and power solutions. The Company's segments include the Power Solutions Group (PSG), the Advanced Solutions Group (ASG) and the Intelligent Sensing Group (ISG). The PSG segment offers a range of analog, discrete, module and integrated semiconductor products. The ASG segment designs and develops analog, mixed-signal, advanced logic, application specific standard products (ASSPs) and application specific integrated circuits (ASICs), radio frequency (RF) and integrated power solutions for a base of end-users in different end-markets. The ISG segment designs and develops complementary metal oxide semiconductor (CMOS) image sensors, image signal processors, single photon detectors, including Silicon photomultipliers (SiPM) and Single photon avalanche diode (SPAD) arrays, as well as actuator drivers for autofocus and image stabilization for a base of end-users in the different end-markets.",
      CommonName: "ON Semiconductor Corp",
      HeadquartersCountry: "United States of America",
      PriceClose: 59.19,
      Volume: 2658846,
    },
    {
      RIC: "MRVL.OQ",
      ESGCombinedScore: 61.9482193320947,
      ESGControversiesScore: 100,
      ESGEmissionsScore: 76.7015706806282,
      ESGEnvironmentalScore: 54.6904861623857,
      ESGGovernanceScore: 80.8092636643238,
      ESGResourceUseScore: 60.6770833333333,
      ESGSocialScore: 55.7956347693201,
      BusinessSummary:
        "Marvell Technology, Inc., through its subsidiaries, is a supplier of infrastructure semiconductor solutions. The Company is engaged in the design, development and sale of integrated circuits. Its product solutions serve five markets, such as data center, carrier infrastructure, enterprise networking, consumer, and automotive/industrial. Its product offerings include custom application-specific integrated circuits (ASICs), electro-optics, Ethernet solutions, fiber channel adapters, processors and storage controllers. It develops custom system-on-a-chip (SoC) solutions tailored to individual customer specifications. Its electro-optical products include pulse amplitude modulation (PAM) and coherent digital signal processors (DSPs), laser drivers, trans-impedance amplifiers (TIAs), silicon photonics and data center interconnect (DCI) solutions. It offers a portfolio of Ethernet solutions spanning controllers, network adapters, physical transceivers and switches.",
      CommonName: "Marvell Technology Inc",
      HeadquartersCountry: "United States of America",
      PriceClose: 37.22,
      Volume: 5489805,
    },
    {
      RIC: "QRVO.OQ",
      ESGCombinedScore: 65.9057216641869,
      ESGControversiesScore: 100,
      ESGEmissionsScore: 63.6125654450261,
      ESGEnvironmentalScore: 60.876253081137,
      ESGGovernanceScore: 81.5028362768244,
      ESGResourceUseScore: 94.0104166666666,
      ESGSocialScore: 60.1107202623825,
      BusinessSummary:
        "Qorvo, Inc. is engaged in the development and commercialization of technologies and products for the wireless, wired and power markets. The Company operates through two segments: Mobile Products (MP) and Infrastructure and Defense Products (IDP). MP is a supplier of cellular, ultra-wideband 802.15.4z (UWB), and wireless fidelity (Wi-Fi) solutions for a variety of applications, including smartphones, wearables, laptops, tablets, and the Internet of Things (IoT). IDP is a supplier of radio frequency (RF), system-on-a-chip (SoC), and power management solutions for applications in wireless infrastructure, defense, Wi-Fi, smart home, automotive, and IoT. Its MP segment supplies RF solutions to global consumer product companies. The IDP segment supplies a diverse portfolio of products with generally longer life cycles to a range of customers. It operates design, sales, and manufacturing facilities located throughout Asia, Europe and North America.",
      CommonName: "Qorvo Inc",
      HeadquartersCountry: "United States of America",
      PriceClose: 82.67,
      Volume: 1011658,
    },
  ],
};
